exp.items = _.shuffle([    
    {
        "label": "bottle_glass_big",
        "object": "bottle",
        "adj1": "glass",
        "adj2": "big",
    },
    {
        "label": "bottle_glass_small",
        "object": "bottle",
        "adj1": "glass",
        "adj2": "small",
    },
    {
        "label": "bottle_plastic_big",
        "object": "bottle",
        "adj1": "plastic",
        "adj2": "big",
    },
    {
        "label": "bottle_plastic_small",
        "object": "bottle",
        "adj1": "plastic",
        "adj2": "small",
    },
    {
        "label": "box_closed_cardboard",
        "object": "box",
        "adj1": "closed",
        "adj2": "cardboard",
    },
    {
        "label": "box_closed_wood",
        "object": "box",
        "adj1": "closed",
        "adj2": "wooden",
    },
    {
        "label": "box_open_cardboard",
        "object": "box",
        "adj1": "open",
        "adj2": "cardboard",
    },
    {
        "label": "box_open_wood",
        "object": "box",
        "adj1": "open",
        "adj2": "wooden",
    },
    {
        "label": "earring_big_round",
        "object": "earring",
        "adj1": "big",
        "adj2": "round",
    },
    {
        "label": "earring_big_triangular",
        "object": "earring",
        "adj1": "big",
        "adj2": "triangular",
    },
    {
        "label": "earring_small_round",
        "object": "earring",
        "adj1": "small",
        "adj2": "round",
    },
    {
        "label": "earring_small_triangular",
        "object": "earring",
        "adj1": "small",
        "adj2": "triangular",
    },
    {
        "label": "frog_spotted_green",
        "object": "frog",
        "adj1": "spotted",
        "adj2": "green",
    },
    {
        "label": "frog_spotted_red",
        "object": "frog",
        "adj1": "spotted",
        "adj2": "red",
    },
    {
        "label": "frog_striped_green",
        "object": "frog",
        "adj1": "striped",
        "adj2": "green",
    },
    {
        "label": "frog_striped_red",
        "object": "frog",
        "adj1": "striped",
        "adj2": "red",
    },
    {
        "label": "hair_curly_blonde",
        "object": "hair",
        "adj1": "curly",
        "adj2": "blond",
    },
    {
        "label": "hair_curly_brown",
        "object": "hair",
        "adj1": "curly",
        "adj2": "brown",
    },
    {
        "label": "hair_straight_blonde",
        "object": "hair",
        "adj1": "straight",
        "adj2": "blond",
    },
    {
        "label": "hair_straight_brown",
        "object": "hair",
        "adj1": "straight",
        "adj2": "brown",
    },
    {
        "label": "man_old_bearded",
        "object": "man",
        "adj1": "old",
        "adj2": "bearded",
    },
    {
        "label": "man_old_cleanshaven",
        "object": "man",
        "adj1": "old",
        "adj2": "clean-shaven",
    },
    {
        "label": "man_young_bearded",
        "object": "man",
        "adj1": "young",
        "adj2": "bearded",
    },
    {
        "label": "man_young_cleanshaven",
        "object": "man",
        "adj1": "young",
        "adj2": "clean-shaven",
    },
    {
        "label": "man2_bearded_glassed",
        "object": "man",
        "adj1": "bearded",
        "adj2": "glasses-wearing",
    },
    {
        "label": "man2_bearded_hatted",
        "object": "man",
        "adj1": "bearded",
        "adj2": "hat-wearing",
    },
    {
        "label": "man2_mustached_glassed",
        "object": "man",
        "adj1": "mustache-touting",
        "adj2": "glasses-wearing",
    },
    {
        "label": "man2_mustached_hatted",
        "object": "man",
        "adj1": "mustache-touting",
        "adj2": "hat-wearing",
    },
    {
        "label": "nails_black_glossy",
        "object": "nails",
        "adj1": "black",
        "adj2": "glossy",
    },
    {
        "label": "nails_black_matte",
        "object": "nails",
        "adj1": "black",
        "adj2": "matte",
    },
    {
        "label": "nails_red_glossy",
        "object": "nails",
        "adj1": "red",
        "adj2": "glossy",
    },
    {
        "label": "nails_red_matte",
        "object": "nails",
        "adj1": "red",
        "adj2": "matte",
    },
    {
        "label": "pencil_long_black",
        "object": "pencil",
        "adj1": "long",
        "adj2": "black",
    },
    {
        "label": "pencil_long_blue",
        "object": "pencil",
        "adj1": "long",
        "adj2": "blue",
    },
    {
        "label": "pencil_short_black",
        "object": "pencil",
        "adj1": "short",
        "adj2": "black",
    },
    {
        "label": "pencil_short_blue",
        "object": "pencil",
        "adj1": "short",
        "adj2": "blue",
    },
    {
        "label": "picture_bw_rectangular",
        "object": "picture",
        "adj1": "black and white",
        "adj2": "rectangular",
    },
    {
        "label": "picture_bw_square",
        "object": "picture",
        "adj1": "black and white",
        "adj2": "square",
    },
    {
        "label": "picture_colored_rectangular",
        "object": "picture",
        "adj1": "colored",
        "adj2": "rectangular",
    },
    {
        "label": "picture_colored_square",
        "object": "picture",
        "adj1": "colored",
        "adj2": "square",
    },
    {
        "label": "shorts_dry_green",
        "object": "shorts",
        "adj1": "dry",
        "adj2": "green",
    },
    {
        "label": "shorts_dry_red",
        "object": "shorts",
        "adj1": "dry",
        "adj2": "red",
    },
    {
        "label": "shorts_wet_green",
        "object": "shorts",
        "adj1": "wet",
        "adj2": "green",
    },
    {
        "label": "shorts_wet_red",
        "object": "shorts",
        "adj1": "wet",
        "adj2": "red",
    },
    {
        "label": "spoon_metal_clean",
        "object": "spoon",
        "adj1": "metal",
        "adj2": "clean",
    },
    {
        "label": "spoon_metal_dirty",
        "object": "spoon",
        "adj1": "metal",
        "adj2": "dirty",
    },
    {
        "label": "spoon_wooden_clean",
        "object": "spoon",
        "adj1": "wooden",
        "adj2": "clean",
    },
    {
        "label": "spoon_wooden_dirty",
        "object": "spoon",
        "adj1": "wooden",
        "adj2": "dirty",
    },
    {
        "label": "table_metal_high",
        "object": "table",
        "adj1": "metal",
        "adj2": "high",
    },
    {
        "label": "table_metal_low",
        "object": "table",
        "adj1": "metal",
        "adj2": "low",
    },
    {
        "label": "table_wood_high",
        "object": "table",
        "adj1": "wooden",
        "adj2": "high",
    },
    {
        "label": "table_wood_low",
        "object": "table",
        "adj1": "wooden",
        "adj2": "low",
    },
    {
        "label": "woman_old_happy",
        "object": "woman",
        "adj1": "old",
        "adj2": "happy",
    },
    {
        "label": "woman_old_sad",
        "object": "woman",
        "adj1": "old",
        "adj2": "sad",
    },
    {
        "label": "woman_young_happy",
        "object": "woman",
        "adj1": "young",
        "adj2": "happy",
    },
    {
        "label": "woman_young_sad",
        "object": "woman",
        "adj1": "young",
        "adj2": "sad",
    },
    {
        "label": "woman2_happy_fat",
        "object": "woman",
        "adj1": "happy",
        "adj2": "fat",
    },
    {
        "label": "woman2_happy_skinny",
        "object": "woman",
        "adj1": "happy",
        "adj2": "skinny",
    },
    {
        "label": "woman2_sad_fat",
        "object": "woman",
        "adj1": "sad",
        "adj2": "fat",
    },
    {
        "label": "woman2_sad_skinny",
        "object": "woman",
        "adj1": "sad",
        "adj2": "skinny",
    },     
]);