exp.items = _.shuffle([    
    {
        "trial_type": "adjective_ordering",
        "label": "bottle_glass_big",
        "object": "bottle",
        "adj1": "glass",
        "adj2": "big",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "bottle_glass_small",
        "object": "bottle",
        "adj1": "glass",
        "adj2": "small",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "bottle_plastic_big",
        "object": "bottle",
        "adj1": "plastic",
        "adj2": "big",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "bottle_plastic_small",
        "object": "bottle",
        "adj1": "plastic",
        "adj2": "small",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "box_closed_cardboard",
        "object": "box",
        "adj1": "closed",
        "adj2": "cardboard",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "box_closed_wood",
        "object": "box",
        "adj1": "closed",
        "adj2": "wood",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "box_open_cardboard",
        "object": "box",
        "adj1": "open",
        "adj2": "cardboard",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "box_open_wood",
        "object": "box",
        "adj1": "open",
        "adj2": "wood",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "cup_empty_glass",
        "object": "cup",
        "adj1": "empty",
        "adj2": "glass",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "cup_empty_metal",
        "object": "cup",
        "adj1": "empty",
        "adj2": "metal",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "cup_full_glass",
        "object": "cup",
        "adj1": "full",
        "adj2": "glass",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "cup_full_metal",
        "object": "cup",
        "adj1": "full",
        "adj2": "metal",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "earring_big_round",
        "object": "earring",
        "adj1": "big",
        "adj2": "round",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "earring_big_triangular",
        "object": "earring",
        "adj1": "big",
        "adj2": "triangular",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "earring_small_round",
        "object": "earring",
        "adj1": "small",
        "adj2": "round",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "earring_small_triangular",
        "object": "earring",
        "adj1": "small",
        "adj2": "triangular",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "hair_curly_blond",
        "object": "hair",
        "adj1": "curly",
        "adj2": "blond",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "hair_curly_brown",
        "object": "hair",
        "adj1": "curly",
        "adj2": "brown",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "hair_straight_blond",
        "object": "hair",
        "adj1": "straight",
        "adj2": "blond",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "hair_straight_brown",
        "object": "hair",
        "adj1": "straight",
        "adj2": "brown",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "man_old_bald",
        "object": "man",
        "adj1": "old",
        "adj2": "bald",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "man_old_bearded",
        "object": "man",
        "adj1": "old",
        "adj2": "bearded",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "man_young_bald",
        "object": "man",
        "adj1": "young",
        "adj2": "bald",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "man_young_bearded",
        "object": "man",
        "adj1": "young",
        "adj2": "bearded",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "pencil_long_black",
        "object": "pencil",
        "adj1": "long",
        "adj2": "black",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "pencil_long_blue",
        "object": "pencil",
        "adj1": "long",
        "adj2": "blue",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "pencil_short_black",
        "object": "pencil",
        "adj1": "short",
        "adj2": "black",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "pencil_short_blue",
        "object": "pencil",
        "adj1": "short",
        "adj2": "blue",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "picture_bw_rectangular",
        "object": "picture",
        "adj1": "bw",
        "adj2": "rectangular",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "picture_bw_square",
        "object": "picture",
        "adj1": "bw",
        "adj2": "square",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "picture_colored_rectangular",
        "object": "picture",
        "adj1": "colored",
        "adj2": "rectangular",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "picture_colored_square",
        "object": "picture",
        "adj1": "colored",
        "adj2": "square",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_dry_green",
        "object": "shorts",
        "adj1": "dry",
        "adj2": "green",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_dry_red",
        "object": "shorts",
        "adj1": "dry",
        "adj2": "red",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_wet_green",
        "object": "shorts",
        "adj1": "wet",
        "adj2": "green",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_wet_red",
        "object": "shorts",
        "adj1": "wet",
        "adj2": "red",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_wrinkled_green",
        "object": "shorts",
        "adj1": "wrinkled",
        "adj2": "green",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "shorts_wrinkled_red",
        "object": "shorts",
        "adj1": "wrinkled",
        "adj2": "red",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "spoon_metal_clean",
        "object": "spoon",
        "adj1": "metal",
        "adj2": "clean",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "spoon_metal_dirty",
        "object": "spoon",
        "adj1": "metal",
        "adj2": "dirty",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "spoon_wooden_clean",
        "object": "spoon",
        "adj1": "wooden",
        "adj2": "clean",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "spoon_wooden_dirty",
        "object": "spoon",
        "adj1": "wooden",
        "adj2": "dirty",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "table_metal_high",
        "object": "table",
        "adj1": "metal",
        "adj2": "high",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "table_metal_low",
        "object": "table",
        "adj1": "metal",
        "adj2": "low",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "table_wood_high",
        "object": "table",
        "adj1": "wood",
        "adj2": "high",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "table_wood_low",
        "object": "table",
        "adj1": "wood",
        "adj2": "low",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "woman_old_happy",
        "object": "woman",
        "adj1": "old",
        "adj2": "happy",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "woman_old_sad",
        "object": "woman",
        "adj1": "old",
        "adj2": "sad",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "woman_young_happy",
        "object": "woman",
        "adj1": "young",
        "adj2": "happy",
    },
    {
        "trial_type": "adjective_ordering",
        "label": "woman_young_sad",
        "object": "woman",
        "adj1": "young",
        "adj2": "sad",
    },    
]);