---
title: "Pragmatics in CTSL - Ordering Preferences (ENGLISH)"
output: rmarkdown::github_document
#output:
  #html_document: default
  #pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import, include=FALSE}
library(tidyverse)
library(wesanderson)
library(ggpubr)
source("helpers.R")
theme_set(theme_bw())
palette = wes_palette("Zissou1")

# load data and format
df = read.csv("../data/ordering-trials.csv", header = TRUE) %>%
  filter(utterance != "bot_check" )

df$response = gsub("\\[","",df$response)
df$response = gsub("\\]","",df$response)
df$response = as.numeric(df$response)
df$left_end = gsub('"',"",df$left_end)
df$right_end = gsub('"',"",df$right_end)
```

```{r data wrangling, include=FALSE}
# averaging ratings of configurations in which an adj appeared in first position (farther from the noun) --> greater values signal that a class’s adjectives are preferred in first position, farther from the noun

# group by first position adjectives on one end (right) -- higher the mean, the more preferred they are in first position
df = df %>%
  mutate(right_end = str_replace(right_end,"black and white","black-and-white")) %>%
  mutate(left_end = str_replace(left_end,"black and white","black-and-white")) %>%
  mutate(adj1=str_replace(adj1,"black and white","black-and-white")) %>%
  mutate(adj2=str_replace(adj2,"black and white", "black-and-white")) %>%
  mutate(first_pos = word(right_end, 1)) %>%
  mutate(second_pos = word(right_end, 2)) %>%
  mutate(response_first_pos= response) %>%
  mutate(response_second_pos = 1-response)

sum = df %>% select(label,object,adj1,adj2) %>% unique()
```

```{r preferenece, echo=FALSE}
# every row gives two datapoints (how much each ordering is preferred)
d = df %>%
  group_by(label,first_pos,second_pos) %>%
  summarise(Mean_first=mean(response_first_pos), Mean_second=mean(response_second_pos)) %>%
  merge(sum, by="label") %>%
  mutate(adj1_m=ifelse(adj1==first_pos,Mean_first,Mean_second)) %>%
  mutate(adj2_m=ifelse(adj2==first_pos,Mean_first,Mean_second)) %>%
  group_by(label) %>%
  mutate(adj1_total_mean=mean(adj1_m),adj2_total_mean=mean(adj2_m)) %>%
  select(label,object,adj1,adj2,adj1_total_mean,adj2_total_mean) %>%
  unique()

d_long = gather(d,adj_no,adj,adj1:adj2,factor_key = TRUE)

# preference for each adjective in 1st position in each configuration
dd = d_long %>%
  mutate(preference=ifelse(adj_no=="adj1",adj1_total_mean,ifelse(adj_no=="adj2",adj2_total_mean,NA))) %>%
  select(label,object,adj,preference)

# collapsed across different configurations
# big from [big-glass-bottle,big-plastic-bottle,big-round-earring,big-triangular-earring]
dd_agr = dd %>%
  group_by(adj) %>%
  summarise(Mean=mean(preference),CILow=ci.low(preference),CIHigh=ci.high(preference),count=n()) %>%
  ungroup() %>%
  mutate(YMin=Mean-CILow, YMax=Mean+CIHigh)

ggplot(dd_agr,(aes(x=reorder(adj, -Mean),y=Mean))) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = YMin, ymax = YMax),width=.25) +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  xlab("adjectives") +
  ylab("mean rating in 1st position")

# more subjective adjectives are preferred farther from the noun
ggsave(file="../graphs/adj_first_pos.pdf",width=8,height=4)
```

```{r subjectivity, echo=FALSE}
# load subjectivity and faultless disagreement agv dataset
load("../../../04_subjectivity/english/data/subjectivity_and_disagreement.Rda")
subjectivity = d_wide

# merge and format
dt = merge(dd,subjectivity, by="adj")
dt_adj = dt %>%
  group_by(adj) %>%
  mutate(naturalness=mean(preference)) %>%
  #mutate(naturalness=preference) %>% 
  select(adj,naturalness,subjectivity,disagreement) %>%
  unique()

ggscatter(dt_adj, x = "subjectivity", y = "naturalness", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "subjectivity", ylab = "naturalness", 
          label = "adj",font.label = c(8, "plain"))
ggsave(file="../graphs/subjectivity-naturalness.pdf")

ggscatter(dt_adj, x = "disagreement", y = "naturalness", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "faultless", ylab = "naturalness",
          label = "adj",font.label = c(8, "plain"))
ggsave(file="../graphs/disagreement-naturalness.pdf")

dt_obj = dt %>%
  mutate(adj_noun = paste(adj,object,sep="-")) %>%
  group_by(adj_noun) %>%
  mutate(naturalness=mean(preference)) %>%
  select(adj,naturalness,subjectivity,disagreement) %>%
  unique()

ggscatter(dt_obj, x = "subjectivity", y = "naturalness", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "subjectivity", ylab = "naturalness", 
          label = "adj_noun",font.label = c(8, "plain"))
ggsave(file="../graphs/subjectivity-naturalness.pdf")

```

```{r subjectivity_score, echo=FALSE}
subj = subjectivity %>% select(adj,subjectivity)

ds = dd %>% 
  merge(sum, by=c("label","object")) %>%
  mutate(other_adj=ifelse(adj==adj1,adj2,ifelse(adj==adj2,adj1,NA))) %>%
  select(label,adj,other_adj,object,preference) %>%
  merge(subj, by.x=c("adj"), by.y=c("adj")) %>%
  merge(subj, by.x=c("other_adj"), by.y=c("adj")) %>%
  mutate(subjectivity_difference=(subjectivity.x-subjectivity.y)) %>%
  mutate(order=paste(adj,other_adj,object,sep=" "))

ggplot(ds,(aes(x=subjectivity_difference,y=preference,color=object))) +
    geom_point(size=2)+
    theme(axis.text.x = element_text(angle = 60, hjust=1)) +
    geom_text(size=2,aes(label=order),hjust=0, vjust=0) +
    #geom_smooth(method=lm,se=FALSE) +
    xlab("subjectivity difference") +
    ylab("mean naturalness score") +
    theme(legend.position = "none")


ggsave(file="../graphs/subjectivity-difference.pdf")
```








